# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=16)),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('ubicacion', models.TextField()),
                ('funciona', models.BooleanField()),
            ],
        ),
    ]
